// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTXVtdx0-5SQmpNbFClxs6Ym92JHIcGzY',
    appId: '1:893685089026:web:732902a9ec68edfdb0b81b',
    messagingSenderId: '893685089026',
    projectId: 'a-green-project',
    authDomain: 'a-green-project.firebaseapp.com',
    storageBucket: 'a-green-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBavkRwkNwgzm6YzjqAZZi_yqTtcvpd5LM',
    appId: '1:893685089026:android:2058a04055d18ce6b0b81b',
    messagingSenderId: '893685089026',
    projectId: 'a-green-project',
    storageBucket: 'a-green-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDmL8v9-faC00-bJgAX12Tp9N-kTRlf0A',
    appId: '1:893685089026:ios:a29820ec59418c13b0b81b',
    messagingSenderId: '893685089026',
    projectId: 'a-green-project',
    storageBucket: 'a-green-project.firebasestorage.app',
    iosBundleId: 'com.example.aGreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDmL8v9-faC00-bJgAX12Tp9N-kTRlf0A',
    appId: '1:893685089026:ios:a29820ec59418c13b0b81b',
    messagingSenderId: '893685089026',
    projectId: 'a-green-project',
    storageBucket: 'a-green-project.firebasestorage.app',
    iosBundleId: 'com.example.aGreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTXVtdx0-5SQmpNbFClxs6Ym92JHIcGzY',
    appId: '1:893685089026:web:c1d3beb92bd472b0b0b81b',
    messagingSenderId: '893685089026',
    projectId: 'a-green-project',
    authDomain: 'a-green-project.firebaseapp.com',
    storageBucket: 'a-green-project.firebasestorage.app',
  );
}
